# Generated by Django 3.2.16 on 2023-05-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ('created_at',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='post',
            new_name='post_comment',
        ),
    ]
